In [1]:
import pandas as pd
import time
import datetime as datetime

In [2]:
df = pd.read_csv('uncleaned_data_location_fixed.csv').drop("Unnamed: 0", axis=1)

In [3]:
pd.set_option('display.max_rows', None)

pd.set_option('display.max_columns', None)

pd.set_option('display.width', None)

pd.set_option('display.max_colwidth', None)

In [4]:
df

,name,rarity,weapon,element,3D-model,region,release_date,days_since_release,banner_versions,banner_dates,roles,pulled_count_TARGET_VARIABLE,constellation_0_pull,constellation_1_pull,constellation_2_pull,constellation_3_pull,constellation_4_pull,constellation_5_pull,constellation_6_pull,constellation_7_pull,asc_stat_bonus_category,lvl_90_HP,lvl_90_ATK,lvl_90_DEF,duplicate_rate,c6_rate,avg_copies_per_player
0,lynette,4,Sword,Anemo,Medium Female,Fontaine,2023-08-16,872,"['4.0', '4.6', '5.6']","['August 16, 2023 – September 5, 2023', 'April 24, 2024 – May 14, 2024', 'May 27, 2025 – June 17, 2025']","Off-Field,DPS",1338383,301409,240308,198054,149152,100295,81006,48706,219453,Anemo DMG Bonus,12397,232,712,0.774796,0.036392,4.440421
1,varesa,5,Catalyst,Electro,Medium Female,Natlan,2025-03-26,284,"['5.5', 'Luna III']","['March 26, 2025 – April 15, 2025', 'December 23, 2025 – January 13, 2026']","On-Field,DPS",93049,69219,11980,6303,1140,575,390,3353,90,CRIT Rate,12699,356,782,0.256102,0.036035,1.344270
2,chongyun,4,Claymore,Cryo,Medium Male,Liyue,2020-09-28,1924,"['1.1', '1.3', '2.0', '2.2', '2.4', '2.7', '3.7', '4.1', '5.4', '5.3']","['December 1, 2020 – December 22, 2020', 'March 2, 2021 – March 16, 2021', 'July 21, 2021 – August 10, 2021', 'October 13, 2021 – November 2, 2021', 'January 5, 2022 – January 25, 2022', 'June 21, 2022 – July 12, 2022', 'May 24, 2023 – June 13, 2023', 'October 17, 2023 – November 7, 2023', 'March 4, 2025 – March 25, 2025', 'January 21, 2025 – February 11, 2025']","Off-Field,DPS,Support",4277322,1330794,971436,690870,433896,259920,158592,98847,332967,ATK%,10984,223,648,0.688872,0.023110,3.214113
3,tighnari,5,Bow,Dendro,Medium Male,Sumeru,2022-08-24,1229,"['3.0', 'Luna I']","['August 24, 2022 – September 9, 2022', 'September 10, 2025 – September 30, 2025']","On-Field,DPS",717953,681601,30666,3741,588,200,108,959,90,Dendro DMG Bonus,10850,268,630,0.050633,0.001336,1.053333
4,jean,5,Sword,Anemo,Tall Female,Mondstadt,2020-09-28,1924,['4.5'],"['March 13, 2024 – April 2, 2024']","Off-Field,Survivability",1341413,1291930,44118,4584,572,65,36,42,66,Healing Bonus,14695,239,769,0.036889,0.000031,1.038302
5,keqing,5,Sword,Electro,Medium Female,Liyue,2020-09-28,1924,"['1.3', '5.3']","['February 17, 2021 – March 2, 2021', 'January 21, 2025 – February 11, 2025']","On-Field,DPS",1342803,1292219,45478,4338,600,35,18,21,94,CRIT DMG,13103,323,799,0.037670,0.000016,1.039145
6,gorou,4,Bow,Geo,Medium Male,Inazuma,2021-12-14,1482,"['2.3', '2.7', '3.3', '4.5', '5.4', '5.6']","['December 14, 2021 – January 4, 2022', 'June 21, 2022 – July 12, 2022', 'December 7, 2022 – December 27, 2022', 'March 13, 2024 – April 2, 2024', 'February 12, 2025 – March 4, 2025', 'May 27, 2025 – June 17, 2025']","Off-Field,Support",2431164,894282,490098,316980,198172,138520,80040,78701,234371,Geo DMG Bonus,9570,183,648,0.632159,0.032372,2.718565
7,layla,4,Sword,Cryo,Medium Female,Sumeru,2022-11-18,1143,"['3.2', '3.6', '4.6', '5.6', 'Luna I']","['November 18, 2022 – December 6, 2022', 'April 12, 2023 – May 2, 2023', 'May 14, 2024 – June 4, 2024', 'May 7, 2025 – May 27, 2025', 'September 10, 2025 – September 30, 2025']","Off-Field,Survivability",1619950,494825,325494,239469,165384,110025,71928,53599,159226,HP%,11092,217,655,0.694543,0.033087,3.273784
8,iansan,4,Polearm,Electro,Short Female,Natlan,2025-03-26,284,"['5.5', '5.7', 'Luna III']","['March 26, 2025 – April 15, 2025', 'July 8, 2025 – July 29, 2025', 'December 23, 2025 – January 13, 2026']","Off-Field,Support,Survivability",629343,161967,131354,111048,65432,43655,27534,30548,57806,ATK%,10657,257,638,0.742641,0.048540,3.885625
9,gaming,4,Claymore,Pyro,Medium Male,Liyue,2024-01-31,704,"['4.4', '4.7', '5.5', 'Luna III', '5.3']","['January 31, 2024 – February 20, 2024', 'June 25, 2024 – July 16, 2024', 'March 26, 2025 – April 15, 2025', 'December 23, 2025 – January 13, 2026', 'January 21, 2025 – February 11, 2025']","On-Field,DPS",1490123,291103,283852,245079,181412,121710,98220,66465,202283,ATK%,11419,302,703,0.804645,0.044604,5.118886
10,noelle,4,Claymore,Geo,Medium Female,Mondstadt,2020-09-28,1924,"['1.0', '1.2', '1.4', '1.5', '2.3', '2.7', '3.2', '4.0', '4.4', '4.7', '4.5']","['October 20, 2020 – November 10, 2020', 'January 12, 2021 – February 2, 2021', 'March 17, 2021 – April 6, 2021', 'April 28, 2021 – May 18, 2021', 'November 24, 2021 – December 14, 2021', 'May 31, 2022 – June 21, 2022', 'November 2, 2022 – November 18, 2022', 'September 5, 2023 – September 26, 2023', 'January 31, 2024 – February 20, 2024', 'June 25, 2024 – July 16, 2024', 'March 13, 2024 – April 2, 2024']","On-Field,DPS,Survivability",4861709,1212158,1015206,791235,532572,347425,228480,152894,581739,DEF%,12071,191,799,0.750672,0.031449,4.010788
11,shikanoin_heizou,4,Catalyst,Anemo,Medium Male,Inazuma,2022-07-13,1271,"['2.8', '3.2', '3.7', '5.2', '5.6']","['July 13, 2022 – August 2, 2022', 'November 18, 2022 – December 6, 2022', 'June 13, 2023 – July 4, 2023', 'December 10, 2024 – December 31, 2024', 'May 27, 2025 – June 17, 2025']","On-Field,DPS",2563870,657490,517588,420084,300704,198360,126318,107422,235904,Anemo DMG Bonus,10657,225,684,0.743556,0.041898,3.899481
12,collei,4,Bow,Dendro,Medium Female,Sumeru,2022-08-24,1229,"['3.0', '3.5', '4.2', '5.1', 'Luna II', 'Luna I']","['August 24, 2022 – September 9, 2022', 'March 1, 2023 – March 21, 2023', 'November 8, 2023 – November 28, 2023', 'October 9, 2024 – October 29, 2024', 'October 22, 2025 – November 11, 2025', 'September 10, 2025 – September 30, 2025']","Off-Field,DPS",2798153,560720,478546,403080,297000,212600,156918,114695,574596,ATK%,9787,200,601,0.799611,0.040990,4.990286
13,mona,5,Catalyst,Hydro,Medium Female,Mondstadt,2020-09-28,1924,['4.5'],"['March 13, 2024 – April 2, 2024']","Off-Field,Support",1340198,1290521,44410,4455,660,65,18,21,48,Energy Recharge,10409,287,653,0.037067,0.000016,1.038494
14,kujou_sara,4,Bow,Electro,Tall Female,Inazuma,2021-09-01,1586,"['2.1', '2.5', '3.3', '4.3', '5.0', '5.6']","['September 1, 2021 – September 21, 2021', 'March 8, 2022 – March 29, 2022', 'December 27, 2022 – January 17, 2023', 'January 9, 2024 – January 30, 2024', 'September 17, 2024 – October 8, 2024', 'May 27, 2025 – June 17, 2025']","Off-Field,Support",4315005,1081658,812620,654357,457800,316750,218760,208936,564124,ATK%,9570,195,628,0.749326,0.048421,3.989251
15,chevreuse,4,Polearm,Pyro,Medium Female,Fontaine,2024-01-09,726,"['4.3', '5.0', '5.3', '5.5', 'Luna III']","['January 9, 2024 – January 30, 2024', 'September 17, 2024 – October 8, 2024', 'January 21, 2025 – February 11, 2025', 'March 26, 2025 – April 15, 2025', 'December 23, 2025 – January 13, 2026']","Off-Field,Support,Survivability",1838324,386748,355512,298881,222016,155630,107142,94164,218232,HP%,11962,193,605,0.789619,0.051223,4.753286
16,yun_jin,4,Polearm,Geo,Medium Female,Liyue,2022-01-05,1460,"['2.4', '2.6', '2.8', '3.4', '3.7', '4.5', 'Luna II', '5.3']","['January 5, 2022 – January 25, 2022', 'March 30, 2022 – April 19, 2022', 'August 2, 2022 – August 23, 2022', 'January 18, 2023 – February 7, 2023', 'May 24, 2023 – June 13, 2023', 'March 13, 2024 – April 2, 2024', 'November 11, 2025 – December 2, 2025', 'January 21, 2025 – February 11, 2025']","Off-Field,Support",3874615,1089014,874188,647175,411748,251815,163752,103264,333659,Energy Recharge,10657,191,734,0.718936,0.026651,3.557911
17,dehya,5,Claymore,Pyro,Tall Female,Sumeru,2023-03-01,1040,"['3.5', 'Luna I']","['March 1, 2023 – March 21, 2023', 'September 10, 2025 – September 30, 2025']","Off-Field,DPS,Survivability",508979,476153,24012,4161,792,595,234,2968,64,HP%,15675,265,628,0.064494,0.005831,1.068940
18,freminet,4,Claymore,Cryo,Medium Male,Fontaine,2023-09-05,852,"['4.0', '4.6']","['September 5, 2023 – September 26, 2023', 'April 24, 2024 – May 14, 2024']","On-Field,DPS",1094506,273494,184626,154905,115300,82490,56862,42868,183961,ATK%,12071,255,708,0.750121,0.039167,4.001938
19,qiqi,5,Sword,Cryo,Short Female,Liyue,2020-09-28,1924,['5.3'],"['January 21, 2025 – February 11, 2025']","Off-Field,Survivability",1334757,1284337,45006,4578,612,70,24,35,95,Healing Bonus,12368,287,922,0.037775,0.000026,1.039258
20,diona,4,Bow,Cryo,Short Female,Mondstadt,2020-11-11,1880,"['1.1', '1.3', '1.5', '2.0', '2.2', '2.5', '3.0', '3.5', '4.1', '5.3', '5.7', '4.5']","['November 11, 2020 – December 1, 2020', 'February 3, 2021 – February 17, 2021', 'April 28, 2021 – May 18, 2021', 'August 10, 2021 – August 31, 2021', 'November 2, 2021 – November 23, 2021', 'February 16, 2022 – March 8, 2022', 'August 24, 2022 – September 9, 2022', 'March 21, 2023 – April 11, 2023', 'September 27, 2023 – October 17, 2023', 'January 1, 2025 – January 21, 2025', 'June 18, 2025 – July 8, 2025', 'March 13, 2024 – April 2, 2024']","Off-Field,Survivability",6776259,1566756,1366338,1092498,771196,522705,350544,240212,866010,Cryo DMG Bonus,9570,212,601,0.768787,0.035449,4.325025
21,mika,4,Polearm,Cryo,Medium Male,Mondstadt,2023-03-21,1020,"['3.5', '3.8', '5.4', '4.5']","['March 21, 2023 – April 11, 2023', 'July 5, 2023 – July 25, 2023', 'March 4, 2025 – March 25, 2025', 'March 13, 2024 – April 2, 2024']","Off-Field,Support,Survivability",1298582,339066,227894,188919,139664,98060,66726,57561,180692,HP%,12506,223,713,0.738895,0.044326,3.829880
22,xingqiu,4,Sword,Hydro,Medium Male,Liyue,2020-09-28,1924,"['1.0', '1.2', '1.3', '1.5', '2.1', '2.4', '3.0', '3.4', '4.1', '4.5', '5.1', '5.8', 'Luna II', '5.3']","['October 20, 2020 – November 10, 2020', 'January 12, 2021 – February 2, 2021', 'March 2, 2021 – March 16, 2021', 'May 18, 2021 – June 8, 2021', 'September 21, 2021 – October 12, 2021', 'January 25, 2022 – February 15, 2022', 'September 9, 2022 – September 27, 2022', 'February 7, 2023 – February 28, 2023', 'September 27, 2023 – October 17, 2023', 'April 2, 2024 – April 23, 2024', 'October 29, 2024 – November 19, 2024', 'July 30, 2025 – August 19, 2025', 'October 22, 2025 – November 11, 2025', 'January 21, 2025 – February 11, 2025']","Off-Field,DPS,Survivability",6183960,1434504,1259108,1022235,726100,496670,335730,222012,687603,ATK%,10222,202,758,0.768028,0.035901,4.310870
23,kirara,4,Sword,Dendro,Medium Female,Inazuma,2023-05-24,956,"['3.7', '4.2', '4.8', '5.6']","['May 24, 2023 – June 13, 2023', 'November 28, 2023 – December 19, 2023', 'July 17, 2024 – August 6, 2024', 'May 27, 2025 – June 17, 2025']","Off-Field,Survivability",872772,353432,190658,120087,67852,40940,22998,21273,55532,HP%,12180,223,546,0.595047,0.024374,2.469420
24,kuki_shinobu,4,Sword,Electro,Medium Female,Inazuma,2022-06-21,1293,"['2.7', '3.1', '3.6', '4.2', '5.1', 'Luna I', '5.6']","['June 21, 2022 – July 12, 2022', 'September 28, 2022 – October 14, 2022', 'April 12, 2023 – May 2, 2023', 'November 28, 2023 – December 19, 2023', 'October 29, 2024 – November 19, 2024', 'September 10, 2025 – September 30, 2025', 'May 27, 2025 – June 17, 2025']","Off-Field,Survivability",2464379,768976,518458,387210,253172,163665,103764,72765,196369,HP%,12289,212,751,0.687964,0.029527,3.204754
25,bennett,4,Sword,Pyro,Medium Male,Mondstadt,2020-09-28,1924,"['1.2', '1.3', '1.6', '2.3', '2.5', '2.8', '3.2', '3.5', '4.0', '4.3', '4.7', '5.0', '5.3', '5.8', 'Luna III', '4.5']","['December 23, 2020 – January 12, 2021', 'February 17, 2021 – March 2, 2021', 'June 29, 2021 – July 20, 2021', 'November 24, 2021 – December 14, 2021', 'March 8, 2022 – March 29, 2022', 'August 2, 2022 – August 23, 2022', 'November 2, 2022 – November 18, 2022', 'March 1, 2023 – March 21, 2023', 'August 16, 2023 – September 5, 2023', 'January 9, 2024 – January 30, 2024', 'June 5, 2024 – June 25, 2024', 'August 28, 2024 – September 17, 2024', 'January 1, 2025 – January 21, 2025', 'August 19, 2025 – September 9, 2025', 'December 3, 2025 – December 23, 2025', 'March 13, 2024 – April 2, 2024']","Off-Field,Support,Survivability",7659164,1775083,1581770,1213152,839452,562730,382812,261968,1042197,Energy Recharge,12397,191,771,0.768241,0.034203,4.314820
26,kachina,4,Polearm,Geo,Short Female,Natlan,2024-08-28,494,"['5.0', '5.3']","['August 28, 2024 – September 17, 2024', 'January 1, 2025 – January 21, 2025']","Off-Field,DPS",1577652,197941,232762,228036,192512,147385,118746,83370,376900,Geo DMG Bonus,11799,217,792,0.874534,0.052844,7.970314
27,candace,4,Polearm,Hydro,Tall Female,Sumeru,2022-09-28,1194,"['3.1', '3.6', '4.3', '5.1', '5.7', 'Luna I']","['September 28, 2022 – October 14, 2022', 'May 2, 2023 – May 23, 2023', 'December 20, 2023 – January 9, 2024', 'October 9, 2024 – October 29, 2024', 'June 18, 2025 – July 8, 2025', 'September 10, 2025 – September 30, 2025']","Off-Field,Support",2563163,615098,507684,405771,287012,191010,124746,91238,340604,HP%,10875,212,683,0.760024,0.035596,4.167081
28,xinyan,4,Claymore,Pyro,Medium Female,Liyue,2020-12-01,1860,"['1.1', '1.3', '1.5', '2.0', '2.5', '2.8', '3.4', '4.4', '5.0', '5.3']","['December 1, 2020 – December 22, 2020', 'February 3, 2021 – February 17, 2021', 'May 18, 2021 – June 8, 2021', 'August 10, 2021 – August 31, 2021', 'March 8, 2022 – March 29, 2022', 'August 2, 2022 – August 23, 2022', 'January 18, 2023 – February 7, 2023', 'February 20, 2024 – March 12, 2024', 'August 28, 2024 – September 17, 2024', 'January 21, 2025 – February 11, 2025']","Off-Field,Survivability",3761404,1203224,815842,576423,373568,235610,146256,93394,317088,ATK%,11201,249,799,0.680113,0.024830,3.126105
29,faruzan,4,Bow,Anemo,Medium Female,Sumeru,2022-12-07,1124,"['3.3', '3.8', '4.4', '4.6', '5.5', 'Luna III', 'Luna I']","['December 7, 2022 – December 27, 2022', 'July 25, 2023 – August 15, 2023', 'January 31, 2024 – February 20, 2024', 'May 14, 2024 – June 4, 2024', 'April 15, 2025 – May 6, 2025', 'December 3, 2025 – December 23, 2025', 'September 10, 2025 – September 30, 2025']","Off-Field,Support",2466547,569077,481932,399459,274316,187260,119316,137186,298001,ATK%,9570,196,628,0.769282,0.055619,4.334294
30,yanfei,4,Catalyst,Pyro,Medium Female,Liyue,2021-04-28,1712,"['1.5', '2.0', '2.2', '2.4', '2.7', '3.3', '3.8', '4.5', '4.8', '5.5', '5.3']","['April 28, 2021 – May 18, 2021', 'July 21, 2021 – August 10, 2021', 'October 13, 2021 – November 2, 2021', 'January 25, 2022 – February 15, 2022', 'May 31, 2022 – June 21, 2022', 'December 7, 2022 – December 27, 2022', 'July 25, 2023 – August 15, 2023', 'April 2, 2024 – April 23, 2024', 'August 6, 2024 – August 27, 2024', 'April 15, 2025 – May 6, 2025', 'January 21, 2025 – February 11, 2025']","On-Field,DPS",6574926,1623669,1442372,1122345,757000,488200,310104,203154,628082,Pyro DMG Bonus,9352,240,587,0.753051,0.030898,4.049425
31,dahlia,4,Sword,Hydro,Medium Male,Mondstadt,2025-06-18,200,['5.7'],"['June 18, 2025 – July 8, 2025']","Off-Field,Survivability",540906,98494,101768,88782,66424,45725,28902,25025,85786,HP%,12506,189,560,0.817909,0.046265,5.491766
32,razor,4,Claymore,Electro,Medium Male,Mondstadt,2020-09-28,1924,"['1.1', '1.4', '1.6', '2.6', '3.2', '3.8', '4.8', '4.5']","['December 1, 2020 – December 22, 2020', 'March 17, 2021 – April 6, 2021', 'June 29, 2021 – July 20, 2021', 'April 19, 2022 – May 31, 2022', 'November 2, 2022 – November 18, 2022', 'July 5, 2023 – July 25, 2023', 'August 6, 2024 – August 27, 2024', 'March 13, 2024 – April 2, 2024']","On-Field,DPS",3244644,987253,663902,495264,326192,205200,131526,85463,349844,Physical DMG Bonus,11962,234,751,0.695728,0.026340,3.286537
33,ifa,4,Catalyst,Anemo,Tall Male,Natlan,2025-05-07,242,"['5.6', '5.8']","['May 7, 2025 – May 27, 2025', 'August 19, 2025 – September 9, 2025']","On-Field,Support,Survivability",506003,139306,113316,86562,56408,35135,21258,16373,37645,Elemental Mastery,10081,178,605,0.724693,0.032358,3.632313
34,charlotte,4,Catalyst,Cryo,Medium Female,Fontaine,2023-11-08,788,"['4.2', '5.4']","['November 8, 2023 – November 28, 2023', 'March 4, 2025 – March 25, 2025']","Off-Field,Survivability",1519781,223837,198684,191085,159212,129430,94542,89390,433601,ATK%,10766,173,546,0.852718,0.058818,6.789677
35,xiangling,4,Polearm,Pyro,Medium Female,Liyue,2020-09-28,1924,"['1.0', '1.2', '1.3', '2.1', '2.3', '2.6', '3.1', '3.7', '4.2', '4.6', '4.8', '5.4', '5.7', '5.3']","['September 28, 2020 – October 18, 2020', 'January 12, 2021 – February 2, 2021', 'March 2, 2021 – March 16, 2021', 'September 1, 2021 – September 21, 2021', 'December 14, 2021 – January 4, 2022', 'March 30, 2022 – April 19, 2022', 'October 14, 2022 – November 1, 2022', 'June 13, 2023 – July 4, 2023', 'November 28, 2023 – December 19, 2023', 'April 24, 2024 – May 14, 2024', 'August 6, 2024 – August 27, 2024', 'February 12, 2025 – March 4, 2025', 'July 8, 2025 – July 29, 2025', 'January 21, 2025 – February 11, 2025']","Off-Field,DPS",5885078,1493505,1245006,950169,648456,415070,271992,179340,681540,Elemental Mastery,10875,225,669,0.746222,0.030474,3.940447
36,sayu,4,Claymore,Anemo,Short Female,Inazuma,2021-08-10,1608,"['2.0', '2.2', '2.6', '3.1', '3.3', '4.0', '5.4', '5.6']","['August 10, 2021 – August 31, 2021', 'November 2, 2021 – November 23, 2021', 'April 19, 2022 – May 31, 2022', 'September 28, 2022 – October 14, 2022', 'December 27, 2022 – January 17, 2023', 'September 5, 2023 – September 26, 2023', 'February 12, 2025 – March 4, 2025', 'May 27, 2025 – June 17, 2025']","Off-Field,Survivability",4769688,1412797,1038398,764727,509672,324115,203844,135051,381084,Elemental Mastery,11854,244,745,0.703797,0.028314,3.376060
37,diluc,5,Claymore,Pyro,Tall Male,Mondstadt,2020-09-28,1924,['4.5'],"['March 13, 2024 – April 2, 2024']","On-Field,DPS",1341794,1291442,44902,4575,656,70,36,28,85,CRIT Rate,12981,335,784,0.037526,0.000021,1.038989
38,xilonen,5,Sword,Geo,Tall Female,Natlan,2024-10-09,452,"['5.1', '5.5', 'Luna III']","['October 9, 2024 – October 29, 2024', 'April 15, 2025 – May 6, 2025', 'December 23, 2025 – January 13, 2026']","Off-Field,Support,Survivability",285712,203944,21998,44358,4248,2855,432,7728,149,DEF%,12405,275,930,0.286190,0.027048,1.400934
39,thoma,4,Polearm,Pyro,Tall Male,Inazuma,2021-11-02,1524,"['2.2', '2.5', '2.8', '3.2', '3.8', '4.1', '4.7', '5.0', '5.6']","['November 2, 2021 – November 23, 2021', 'February 16, 2022 – March 8, 2022', 'July 13, 2022 – August 2, 2022', 'November 18, 2022 – December 6, 2022', 'July 5, 2023 – July 25, 2023', 'October 17, 2023 – November 7, 2023', 'June 5, 2024 – June 25, 2024', 'September 17, 2024 – October 8, 2024', 'May 27, 2025 – June 17, 2025']","Off-Field,Survivability",5818086,1481574,1232860,965352,667380,443180,277734,202657,547349,ATK%,10331,202,751,0.745350,0.034832,3.926963
40,yaoyao,4,Polearm,Dendro,Short Female,Liyue,2023-01-18,1082,"['3.4', '3.7', '4.4', '5.2', '5.7', 'Luna II', '5.3']","['January 18, 2023 – February 7, 2023', 'June 13, 2023 – July 4, 2023', 'February 20, 2024 – March 12, 2024', 'December 10, 2024 – December 31, 2024', 'July 8, 2025 – July 29, 2025', 'October 22, 2025 – November 11, 2025', 'January 21, 2025 – February 11, 2025']","Off-Field,Survivability",2092017,525384,428354,335007,237172,160190,111546,72933,221434,HP%,12289,212,751,0.748862,0.034863,3.981882
41,beidou,4,Claymore,Electro,Tall Female,Liyue,2020-09-28,1924,"['1.1', '1.3', '1.5', '2.1', '2.4', '3.1', '3.4', '4.2', '4.6', '5.5', '5.3']","['November 11, 2020 – December 1, 2020', 'February 3, 2021 – February 17, 2021', 'May 18, 2021 – June 8, 2021', 'September 21, 2021 – October 12, 2021', 'January 25, 2022 – February 15, 2022', 'October 14, 2022 – November 1, 2022', 'February 7, 2023 – February 28, 2023', 'November 8, 2023 – November 28, 2023', 'May 14, 2024 – June 4, 2024', 'April 15, 2025 – May 6, 2025', 'January 21, 2025 – February 11, 2025']","Off-Field,DPS,Survivability",5583283,1279843,1065398,856212,609772,422445,294420,206339,848854,Electro DMG Bonus,13050,225,648,0.770772,0.036957,4.362475

In [5]:
df['num_banners'] = df['banner_versions'].apply(lambda x: len(x.split(',')) if pd.notna(x) and x != '' else 0)

df['months_since_release'] = df['days_since_release'] / 30.5

four_star_names = df[df['rarity'] == 4]['name'].tolist()

standard_5stars = ['diluc', 'jean', 'keqing', 'mona', 'qiqi', 'tighnari', 'dehya', 'yumemizuki_mizuki']

standard_characters = standard_5stars + four_star_names

df['is_standard_banner'] = df['name'].isin(standard_characters).astype(int)

for role in ['Off-Field', 'On-Field', 'Support', 'Survivability', 'DPS']:
    df[f'role_{role.replace("-", "_")}'] = df['roles'].apply(
        lambda x: 1 if pd.notna(x) and role in str(x) else 0
    )

archons = ['venti', 'zhongli', 'raiden_shogun', 'nahida', 'furina', 'mavuika']
df['is_archon'] = df['name'].isin(archons).astype(int)

In [6]:
necessary_columns = [
    'pulled_count_TARGET_VARIABLE',
    
    'rarity', 'weapon', 'element', 'region', 'asc_stat_bonus_category', '3D-model',
    
    'lvl_90_HP', 'lvl_90_ATK', 'lvl_90_DEF',

    'months_since_release', 'num_banners',
    
    'is_archon', 'is_standard_banner',
    
    'role_Off_Field', 'role_On_Field', 'role_Support', 'role_Survivability', 'role_DPS',

    'duplicate_rate', 'c6_rate', 'avg_copies_per_player'
]

df_filtered = df[necessary_columns]

In [7]:
df_filtered.columns

Index(['pulled_count_TARGET_VARIABLE', 'rarity', 'weapon', 'element', 'region',
       'asc_stat_bonus_category', '3D-model', 'lvl_90_HP', 'lvl_90_ATK',
       'lvl_90_DEF', 'months_since_release', 'num_banners', 'is_archon',
       'is_standard_banner', 'role_Off_Field', 'role_On_Field', 'role_Support',
       'role_Survivability', 'role_DPS', 'duplicate_rate', 'c6_rate',
       'avg_copies_per_player'],
      dtype='object')

In [8]:
df_filtered

,pulled_count_TARGET_VARIABLE,rarity,weapon,element,region,asc_stat_bonus_category,3D-model,lvl_90_HP,lvl_90_ATK,lvl_90_DEF,months_since_release,num_banners,is_archon,is_standard_banner,role_Off_Field,role_On_Field,role_Support,role_Survivability,role_DPS,duplicate_rate,c6_rate,avg_copies_per_player
0,1338383,4,Sword,Anemo,Fontaine,Anemo DMG Bonus,Medium Female,12397,232,712,28.590164,3,0,1,1,0,0,0,1,0.774796,0.036392,4.440421
1,93049,5,Catalyst,Electro,Natlan,CRIT Rate,Medium Female,12699,356,782,9.311475,2,0,0,0,1,0,0,1,0.256102,0.036035,1.344270
2,4277322,4,Claymore,Cryo,Liyue,ATK%,Medium Male,10984,223,648,63.081967,10,0,1,1,0,1,0,1,0.688872,0.023110,3.214113
3,717953,5,Bow,Dendro,Sumeru,Dendro DMG Bonus,Medium Male,10850,268,630,40.295082,2,0,1,0,1,0,0,1,0.050633,0.001336,1.053333
4,1341413,5,Sword,Anemo,Mondstadt,Healing Bonus,Tall Female,14695,239,769,63.081967,1,0,1,1,0,0,1,0,0.036889,0.000031,1.038302
5,1342803,5,Sword,Electro,Liyue,CRIT DMG,Medium Female,13103,323,799,63.081967,2,0,1,0,1,0,0,1,0.037670,0.000016,1.039145
6,2431164,4,Bow,Geo,Inazuma,Geo DMG Bonus,Medium Male,9570,183,648,48.590164,6,0,1,1,0,1,0,0,0.632159,0.032372,2.718565
7,1619950,4,Sword,Cryo,Sumeru,HP%,Medium Female,11092,217,655,37.475410,5,0,1,1,0,0,1,0,0.694543,0.033087,3.273784
8,629343,4,Polearm,Electro,Natlan,ATK%,Short Female,10657,257,638,9.311475,3,0,1,1,0,1,1,0,0.742641,0.048540,3.885625
9,1490123,4,Claymore,Pyro,Liyue,ATK%,Medium Male,11419,302,703,23.081967,5,0,1,0,1,0,0,1,0.804645,0.044604,5.118886
10,4861709,4,Claymore,Geo,Mondstadt,DEF%,Medium Female,12071,191,799,63.081967,11,0,1,0,1,0,1,1,0.750672,0.031449,4.010788
11,2563870,4,Catalyst,Anemo,Inazuma,Anemo DMG Bonus,Medium Male,10657,225,684,41.672131,5,0,1,0,1,0,0,1,0.743556,0.041898,3.899481
12,2798153,4,Bow,Dendro,Sumeru,ATK%,Medium Female,9787,200,601,40.295082,6,0,1,1,0,0,0,1,0.799611,0.040990,4.990286
13,1340198,5,Catalyst,Hydro,Mondstadt,Energy Recharge,Medium Female,10409,287,653,63.081967,1,0,1,1,0,1,0,0,0.037067,0.000016,1.038494
14,4315005,4,Bow,Electro,Inazuma,ATK%,Tall Female,9570,195,628,52.000000,6,0,1,1,0,1,0,0,0.749326,0.048421,3.989251
15,1838324,4,Polearm,Pyro,Fontaine,HP%,Medium Female,11962,193,605,23.803279,5,0,1,1,0,1,1,0,0.789619,0.051223,4.753286
16,3874615,4,Polearm,Geo,Liyue,Energy Recharge,Medium Female,10657,191,734,47.868852,8,0,1,1,0,1,0,0,0.718936,0.026651,3.557911
17,508979,5,Claymore,Pyro,Sumeru,HP%,Tall Female,15675,265,628,34.098361,2,0,1,1,0,0,1,1,0.064494,0.005831,1.068940
18,1094506,4,Claymore,Cryo,Fontaine,ATK%,Medium Male,12071,255,708,27.934426,2,0,1,0,1,0,0,1,0.750121,0.039167,4.001938
19,1334757,5,Sword,Cryo,Liyue,Healing Bonus,Short Female,12368,287,922,63.081967,1,0,1,1,0,0,1,0,0.037775,0.000026,1.039258
20,6776259,4,Bow,Cryo,Mondstadt,Cryo DMG Bonus,Short Female,9570,212,601,61.639344,12,0,1,1,0,0,1,0,0.768787,0.035449,4.325025
21,1298582,4,Polearm,Cryo,Mondstadt,HP%,Medium Male,12506,223,713,33.442623,4,0,1,1,0,1,1,0,0.738895,0.044326,3.829880
22,6183960,4,Sword,Hydro,Liyue,ATK%,Medium Male,10222,202,758,63.081967,14,0,1,1,0,0,1,1,0.768028,0.035901,4.310870
23,872772,4,Sword,Dendro,Inazuma,HP%,Medium Female,12180,223,546,31.344262,4,0,1,1,0,0,1,0,0.595047,0.024374,2.469420
24,2464379,4,Sword,Electro,Inazuma,HP%,Medium Female,12289,212,751,42.393443,7,0,1,1,0,0,1,0,0.687964,0.029527,3.204754
25,7659164,4,Sword,Pyro,Mondstadt,Energy Recharge,Medium Male,12397,191,771,63.081967,16,0,1,1,0,1,1,0,0.768241,0.034203,4.314820
26,1577652,4,Polearm,Geo,Natlan,Geo DMG Bonus,Short Female,11799,217,792,16.196721,2,0,1,1,0,0,0,1,0.874534,0.052844,7.970314
27,2563163,4,Polearm,Hydro,Sumeru,HP%,Tall Female,10875,212,683,39.147541,6,0,1,1,0,1,0,0,0.760024,0.035596,4.167081
28,3761404,4,Claymore,Pyro,Liyue,ATK%,Medium Female,11201,249,799,60.983607,10,0,1,1,0,0,1,0,0.680113,0.024830,3.126105
29,2466547,4,Bow,Anemo,Sumeru,ATK%,Medium Female,9570,196,628,36.852459,7,0,1,1,0,1,0,0,0.769282,0.055619,4.334294
30,6574926,4,Catalyst,Pyro,Liyue,Pyro DMG Bonus,Medium Female,9352,240,587,56.131148,11,0,1,0,1,0,0,1,0.753051,0.030898,4.049425
31,540906,4,Sword,Hydro,Mondstadt,HP%,Medium Male,12506,189,560,6.557377,1,0,1,1,0,0,1,0,0.817909,0.046265,5.491766
32,3244644,4,Claymore,Electro,Mondstadt,Physical DMG Bonus,Medium Male,11962,234,751,63.081967,8,0,1,0,1,0,0,1,0.695728,0.026340,3.286537
33,506003,4,Catalyst,Anemo,Natlan,Elemental Mastery,Tall Male,10081,178,605,7.934426,2,0,1,0,1,1,1,0,0.724693,0.032358,3.632313
34,1519781,4,Catalyst,Cryo,Fontaine,ATK%,Medium Female,10766,173,546,25.836066,2,0,1,1,0,0,1,0,0.852718,0.058818,6.789677
35,5885078,4,Polearm,Pyro,Liyue,Elemental Mastery,Medium Female,10875,225,669,63.081967,14,0,1,1,0,0,0,1,0.746222,0.030474,3.940447
36,4769688,4,Claymore,Anemo,Inazuma,Elemental Mastery,Short Female,11854,244,745,52.721311,8,0,1,1,0,0,1,0,0.703797,0.028314,3.376060
37,1341794,5,Claymore,Pyro,Mondstadt,CRIT Rate,Tall Male,12981,335,784,63.081967,1,0,1,0,1,0,0,1,0.037526,0.000021,1.038989
38,285712,5,Sword,Geo,Natlan,DEF%,Tall Female,12405,275,930,14.819672,3,0,0,1,0,1,1,0,0.286190,0.027048,1.400934
39,5818086,4,Polearm,Pyro,Inazuma,ATK%,Tall Male,10331,202,751,49.967213,9,0,1,1,0,0,1,0,0.745350,0.034832,3.926963
40,2092017,4,Polearm,Dendro,Liyue,HP%,Short Female,12289,212,751,35.475410,7,0,1,1,0,0,1,0,0.748862,0.034863,3.981882
41,5583283,4,Claymore,Electro,Liyue,Electro DMG Bonus,Tall Female,13050,225,648,63.081967,11,0,1,1,0,0,1,1,0.770772,0.036957,4.362475
42,1109082,4,Bow,Electro,Sumeru,Elemental Mastery,Medium Male,9787,227,560,18.950820,4,0,1,0,1,0,0,1,0.755583,0.032757,4.091376
43,4611626,4,Catalyst,Hydro,Mondstadt,HP%,Medium Female,9787,159,669,63.081967,13,0,1,1,0,0,1,0,0.712895,0.027257,3.483043
44,419747,4,Claymore,Hydro,Nod-Krai,Elemental Mastery,Short Female,11201,242,607,3.803279,1,0,1,1,0,0,0,1,0.864923,0.050130,7.403206
45,1089366,4,Claymore,Dendro,Sumeru,Elemental Mastery,Tall Male,11962,234,751,32.065574,3,0,1,0,1,0,0,1,0.689166,0.035541,3.217151
46,3880165,4,Bow,Electro,Mondstadt,ATK%,Medium Female,9189,244,594,63.081967,11,0,1,1,0,0,0,1,0.708179,0.028969,3.426754
47,5337889,4,Catalyst,Anemo,Mondstadt,Anemo DMG Bonus,Medium Female,9244,170,703,63.081967,12,0,1,1,0,1,0,0,0.750580,0.032029,4.009308
48,893765,4,Bow,Electro,Natlan,ATK%,Tall Male,9244,244,587,13.442623,3,0,1,1,0,0,0,1,0.729412,0.035197,3.695657
49,6055321,4,Polearm,Cryo,Mondstadt,ATK%,Tall Female,12289,240,710,56.852459,12,0,1,1,0,0,0,1,0.725196,0.026098,3.638963
50,5201396,4,Catalyst,Geo,Liyue,Geo DMG Bonus,Tall Female,9787,212,573,63.081967,10,0,1,0,1,0,0,1,0.733760,0.028494,3.756014
51,488077,4,Catalyst,Anemo,Liyue,ATK%,Medium Female,9244,251,580,11.409836,2,0,1,1,0,0,1,1,0.777074,0.039111,4.485796
52,2542518,4,Claymore,Electro,Sumeru,HP%,Short Female,12397,223,723,39.770492,7,0,1,1,0,0,1,0,0.759984,0.038955,4.166382
53,183773,4,Bow,Anemo,Nod-Krai,Healing Bonus,Medium Female,9646,223,580,1.049180,1,0,1,1,0,1,1,0,0.820006,0.062278,5.555747
54,66275,5,Sword,Pyro,Mondstadt,CRIT DMG,Medium Male,12430,347,822,1.049180,1,0,0,1,0,1,0,1,0.302678,0.059042,1.434058
55,290312,5,Bow,Anemo,Mondstadt,Energy Recharge,Medium Male,10531,263,669,63.081967,7,1,0,1,0,1,0,1,0.065271,0.003183,1.069829
56,695635,5,Polearm,Geo,Liyue,Geo DMG Bonus,Tall Male,14695,251,738,60.983607,7,1,0,1,0,1,1,0,0.137213,0.005706,1.159034
57,387194,5,Polearm,Pyro,Snezhnaya,CRIT DMG,Tall Female,13103,342,765,20.327869,3,0,0,0,1,0,0,1,0.367684,0.070670,1.581487
58,669225,5,Sword,Hydro,Fontaine,CRIT Rate,Medium Female,15307,244,696,25.836066,4,1,0,1,0,1,1,1,0.458989,0.089735,1.848392
59,72343,5,Catalyst,Dendro,Nod-Krai,CRIT DMG,Tall Female,12704,344,799,2.426230,1,0,0,0,1,0,0,1,0.242041,0.059992,1.319333
60,134582,5,Polearm,Electro,Nod-Krai,CRIT DMG,Tall Male,12491,352,809,3.147541,1,0,0,0,1,0,0,1,0.393106,0.041818,1.647734
61,629547,5,Bow,Hydro,Liyue,CRIT Rate,Tall Female,14450,244,548,43.081967,5,0,0,1,0,0,0,1,0.274404,0.047290,1.378177
62,133265,5,Catalyst,Dendro,Nod-Krai,Elemental Mastery,Tall Female,10654,255,669,3.803279,1,0,0,1,0,1,0,0,0.219645,0.017491,1.281468
63,652085,5,Catalyst,Dendro,Sumeru,Elemental Mastery,Short Female,10360,299,630,38.000000,5,1,0,1,0,1,0,1,0.295747,0.038613,1.419944
64,136933,5,Bow,Anemo,Natlan,CRIT Rate,Tall Female,9797,347,615,13.442623,2,0,0,0,1,0,0,1,0.284979,0.058123,1.398560
65,163623,5,Catalyst,Hydro,Natlan,CRIT Rate,Medium Female,15185,182,570,16.196721,2,0,0,0,1,0,0,1,0.236409,0.033027,1.309602
66,220519,5,Catalyst,Cryo,Natlan,Elemental Mastery,Medium Female,11634,127,763,12.065574,2,0,0,1,0,1,1,0,0.202645,0.042409,1.254146
67,63137,5,Polearm,Electro,Nod-Krai,CRIT Rate,Medium Female,12613,330,828,5.180328,2,0,0,1,0,0,1,1,0.114560,0.012972,1.129383
68,61284,5,Polearm,Dendro,Fontaine,CRIT DMG,Medium Female,13568,335,730,16.918033,2,0,0,1,0,0,0,1,0.133477,0.026157,1.154037
69,309884,5,Claymore,Pyro,Natlan,CRIT DMG,Tall Female,12552,359,792,12.065574,2,1,0,1,1,1,0,1,0.321682,0.074273,1.474234
70,286032,5,Polearm,Cryo,Liyue,ATK%,Tall Female,12993,304,830,47.868852,4,0,0,1,0,1,0,0,0.213539,0.041383,1.271519
71,202072,5,Sword,Cryo,Extra-Terresterial,CRIT DMG,Medium Female,12417,359,806,6.557377,1,0,0,0,1,0,0,1,0.264505,0.069836,1.359628
72,143622,5,Claymore,Dendro,Natlan,CRIT DMG,Medium Male,12858,332,802,15.540984,2,0,0,0,1,0,0,1,0.246731,0.027245,1.327547
73,1221840,5,Polearm,Electro,Inazuma,Energy Recharge,Tall Female,12907,337,789,52.000000,6,1,0,0,1,1,0,1,0.338379,0.016689,1.511439
74,121147,5,Polearm,Cryo,Fontaine,CRIT Rate,Medium Female,13348,347,732,7.934426,1,0,0,1,0,1,1,1,0.181127,0.013521,1.221191
75,217896,5,Claymore,Geo,Fontaine,CRIT DMG,Tall Female,12650,352,793,24.459016,3,0,0,0,1,0,0,1,0.157332,0.041474,1.186707
76,177051,5,Catalyst,Anemo,Liyue,ATK%,Tall Female,10409,335,573,23.081967,2,0,0,1,0,1,1,0,0.250205,0.027992,1.333697
77,144639,5,Catalyst,Cryo,Fontaine,CRIT DMG,Tall Male,13593,311,763,26.557377,2,0,0,0,1,0,0,1,0.382172,0.052316,1.618574
78,38342,5,Bow,Hydro,Fontaine,HP%,Short Female,13348,193,500,18.295082,2,0,0,1,0,1,1,0,0.201137,0.060247,1.251779
79,16854,5,Catalyst,Anemo,Inazuma,Elemental Mastery,Medium Female,12736,215,757,10.688525,1,0,1,0,1,0,1,1,0.091136,0.015367,1.100274
80,159973,5,Sword,Electro,Fontaine,CRIT Rate,Tall Female,12956,337,784,18.950820,2,0,0,0,1,0,0,1,0.235940,0.060648,1.308797
81,411269,5,Catalyst,Hydro,Fontaine,CRIT DMG,Tall Male,14695,208,576,27.213115,4,0,0,0,1,0,0,1,0.338404,0.036458,1.511496
82,106078,5,Bow,Pyro,Fontaine,CRIT Rate,Medium Male,11021,318,538,28.590164,3,0,0,0,1,0,0,1,0.182828,0.028837,1.223732
83,796192,5,Polearm,Pyro,Liyue,CRIT DMG,Medium Female,15552,106,876,58.000000,5,0,0,0,1,0,0,1,0.283399,0.008502,1.395477
84,77589,5,Sword,Geo,Inazuma,CRIT Rate,Medium Female,11438,323,953,21.704918,3,0,0,1,0,0,0,1,0.367217,0.137855,1.580321
85,868690,5,Sword,Anemo,Inazuma,Elemental Mastery,Medium Male,13348,297,807,54.098361,6,0,0,1,0,1,0,0,0.214425,0.009839,1.272953
86,221754,5,Sword,Hydro,Sumeru,HP%,Medium Female,15185,230,729,38.622951,4,0,0,1,0,1,0,1,0.185652,0.037943,1.227976
87,227842,5,Sword,Dendro,Sumeru,Dendro DMG Bonus,Tall Male,13348,313,782,35.475410,4,0,0,0,1,0,0,1,0.178303,0.037974,1.216994
88,124712,5,Catalyst,Dendro,Liyue,HP%,Tall Male,13348,193,500,32.065574,4,0,0,1,0,1,1,0,0.201079,0.021273,1.251689
89,356775,5,Catalyst,Anemo,Sumeru,CRIT Rate,Medium Male,10164,328,607,36.852459,4,0,0,0,1,0,0,1,0.315157,0.054446,1.460188
90,372248,5,Claymore,Geo,Inazuma,CRIT Rate,Tall Male,12858,227,959,48.590164,5,0,0,0,1,0,0,1,0.228872,0.027963,1.296801
91,493600,5,Catalyst,Electro,Inazuma,CRIT Rate,Tall Female,10372,340,569,46.491803,5,0,0,1,0,0,0,1,0.236209,0.045976,1.309260
92,418311,5,Polearm,Anemo,Liyue,CRIT Rate,Medium Male,12736,349,799,58.885246,6,0,0,0,1,0,0,1,0.148665,0.011915,1.174625
93,373643,5,Bow,Pyro,Inazuma,CRIT Rate,Medium Female,10164,323,615,52.721311,6,0,0,0,1,0,0,1,0.167569,0.020289,1.201301
94,701615,5,Sword,Cryo,Inazuma,CRIT DMG,Medium Female,12858,342,784,53.377049,5,0,0,0,1,0,0,1,0.183250,0.021181,1.224365
95,199686,5,Polearm,Electro,Sumeru,CRIT DMG,Medium Male,12491,318,859,39.147541,4,0,0,0,1,0,0,1,0.214707,0.026361,1.273410
96,359860,5,Sword,Hydro,Inazuma,CRIT DMG,Tall Male,13715,299,769,45.114754,4,0,0,0,1,0,0,1,0.148491,0.028867,1.174386
97,379509,5,Bow,Hydro,Snezhnaya,Hydro DMG Bonus,Tall Male,13103,301,815,61.639344,6,0,0,0,1,0,0,1,0.160895,0.008448,1.191746
98,420336,5,Catalyst,Hydro,Inazuma,Hydro DMG Bonus,Medium Female,13471,234,657,51.344262,5,0,0,1,0,1,1,0,0.110985,0.006595,1.124840
99,340340,5,Claymore,Cryo,Mondstadt,CRIT DMG,Tall Female,13226,342,751,55.475410,4,0,0,0,1,0,0,1,0.200414,0.034060,1.250648
100,181138,5,Catalyst,Pyro,Mondstadt,Pyro DMG Bonus,Short Female,10287,311,615,62.360656,5,0,0,0,1,0,0,1,0.109530,0.004869,1.123002
101,400978,5,Bow,Cryo,Liyue,CRIT DMG,Medium Female,9797,335,630,59.606557,5,0,0,0,1,0,0,1,0.166468,0.018976,1.199714
102,237976,5,Sword,Geo,Mondstadt,Geo DMG Bonus,Medium Male,13226,251,876,60.262295,4,0,0,1,0,0,0,1,0.098266,0.004530,1.108975

In [9]:
df_filtered.to_csv('cleaned_data.csv')